# .travis.yml
before_deploy: "echo 'deploy start'"
deploy:
    provider: firebase
    token:
        secure: '1/Co2rFNFnfZIcvXyGr9S670qupI6qCPbvJ4solkuQSq8'
    project: 'im-home-demo'
language: node_js
node_js:
    - '8'
before_install:
    - npm install -g yarn --cache-min 999999999
install:
    - cd ./front
    - yarn
