# .travis.yml
language: node_js
node_js:
    - '8'
branches:
    only:
        - travis-test
before_install:
    - npm install -g yarn --cache-min 999999999
install:
    - cd ./front
    - yarn
after_success:
    - cp -r ./public ../server/public
    - cd ../server
deploy:
    provider: heroku
    api_key: ...
notifications:
    email:
        on_failure: change
        on_success: change
